fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      # - id: pretty-format-json
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.21.0
    hooks:
      - id: eslint
        files: \.([jt]sx?|vue)$ # *.js, *.jsx, *.ts, *.tsx and *.vue
        types: [file]
        additional_dependencies:
          - eslint@8.6.0
          - eslint-config-prettier@8.3.0
          - eslint-plugin-jest@25.3.4
          - eslint-plugin-vue@8.2.0
          - vue-eslint-parser@8.0.1
          - jest@27.4.7
